version: '3.8'

services:
  discord-bot:
    # "build: ." heißt: Nimm das Dockerfile aus dem aktuellen Ordner
    build: .
    container_name: discordbot
    # Startet den Bot automatisch neu, wenn er abstürzt oder der Pi neu startet
    restart: unless-stopped
    # Hier sagen wir: "Nimm die Werte, die wir in Portainer eingeben"
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL=${CHANNEL}
      - OLLAMA_URL=http://ollama:11434
      - FROG_API_URL=http://frogAPI:4444/randomfrog
    volumes:
      - bot_data:/app/data
    depends_on:
      - ollama
    networks:
      - default
      - shared-frog-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    privileged: true
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - default

volumes:
  bot_data:
  ollama_data:

networks:
  default:
  shared-frog-net:
    external: true